#
# LoPresti smart home - docker files for Home Assistant
#
##############################################################

version: "2.3"

services:
  # InfluxDB/Grafana server
  influxdb-grafana:
    build:
     context: .
     dockerfile: grafana.Dockerfile
    image: influxdb-grafana:glp
    container_name: influxdb-grafana
    hostname: influxdb-grafana
    stdin_open: true
    tty: true
    restart: always

