#
# LoPresti smart home - configuration file for Home Assistant
#
##############################################################

# General HA configuration
############################

homeassistant:
  name: !secret ha_name
  # location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  # altitude above sea level in meters, impacts weather/sunrise data
  elevation: !secret ha_elevation
  unit_system: metric
  time_zone: Europe/Zurich
  # custom icons and friendly names go there
  customize: !include customizations.yaml

# include all layout/grouping
group: !include groups.yaml

# include all scenes
scene: !include scenes.yaml

# the automation rules are split per area
#automation:
  # Tenda veranda e serrande
#  - !include automations/covers.yaml
  # Presa comandata lume
#  - !include automations/lume.yaml
  # Irrigazione
#  - !include automations/irrigazione.yaml
  # Cucu'
#  - !include automations/cucu.yaml

logger:
  default: warn
  logs:
    homeassistant.components.device_tracker: critical
    homeassistant.components.camera: info
    homeassistant.components.automation: debug
    homeassistant.components.sensor: debug
    homeassistant.components.sensor.command_line: warn
    homeassistant.components.scene: debug
    homeassistant.components.switch: info
    homeassistant.components.cover: info

# Enables the frontend
frontend:

# Enables the configuration tab
config:

# Login and SSL
http:
  api_password: !secret http_password
  base_url: !secret http_base_url
  ssl_certificate: /config/SSLcertificate.crt
  ssl_key: /config/SSLprivatekey.key
  ip_ban_enabled: True
  login_attempts_threshold: 5
  trusted_networks:
    - 192.168.0.0/24

# Checks for available updates and reports used components
updater:
  include_used_components: True

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables events recording
recorder:
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun   # Don't record Sun/Moon data
      - sensor.moon
      - sensor.last_boot

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Text to speech
tts:
  platform: google
  language: 'it'

# Zones
zone 1:
  name: CERN
  latitude: 46.232175
  longitude: 6.050528
  radius: 600

# Useful links
weblink:
  entities:
    - name: QNAP administration
      url: https://lopresti.myqnapcloud.com
    - name: Onkyo web interface
      url: http://192.168.1.30
    - name: NetAtmo station
      url: https://my.netatmo.com/app/station
    - name: WUnderground station
      url: https://www.wunderground.com/personal-weather-station/dashboard?ID=IMEYRIN21
    - name: Somfy Tahoma
      url: https://www.tahomalink.com

panel_iframe:
  router:
    title: Router
    url: https://sunrise.box

# Custom cloud services
#########################

# Pushbullet
notify:
  platform: pushbullet
  name: hass
  api_key: !secret pushbullet_api_key

# IFTTT
#ifttt:
#  key: !secret ifttt_key

# Sensors and devices
#########################

# MQTT broker (mosquitto) running on the QNAP
mqtt:
  broker: 192.168.1.48

# Track mobile phones
device_tracker:
  - platform: nmap_tracker
    home_interval: 10   # minutes
    hosts:
    - 192.168.1.51   # Giu
    - 192.168.1.52   # Isa

#  - platform: owntracks

# To get router statistics
upnp:
  port_mapping:

# NetAtmo weather station
#netatmo:
#  api_key: !secret netatmo_api_key
#  secret_key: !secret netatmo_secret_key
#  username: !secret netatmo_user
#  password: !secret netatmo_password
#  discovery: False

# DLink camera
camera:
  - platform: generic
    name: Salone-Ingresso
    still_image_url: http://192.168.1.4/image.jpg
    username: admin
    password: !secret camera_password

# MotoG camera
android_ip_webcam:
  name: Veranda
  host: 192.168.1.21
  username: admin
  password: !secret camera_password
  sensors:
    - motion
  switches:
    - focus
    - torch
    - video_recording
    - overlay

# Onkyo amplifier
media_player:
  - platform: onkyo
    host: 192.168.1.30
    name: Amplificatore Onkyo
    sources:
      dvd: 'BD/DVD'
      video2: 'Cable TV'
      video6: 'NAS'
      network: 'Network'
      aux1: 'Aux'
      #tuner: 'Tuner'
      #dlna: 'DLNA'
      #internet-radio: 'Radio'

# Kodi player in QNAP/HybridDesk Station
  - platform: kodi
    name: Kodi player in QNAP
    host: 192.168.1.48

# Edimax power socket
switch:
  - platform: edimax
    host: 192.168.1.40
    name: Smartplug
    password: !secret edimax_password

# KIRA IR remote control
kira:
  remotes:
    - name: kira_remote
      host: 192.168.1.31

# Somfy Tahoma for shutters/roof/store
cover:
#  - platform: somfytahoma
#    username: !secret somfy_user
#    password: !secret somfy_password
  - platform: command_line
    covers:
      cucina:
        command_open: /config/pytahoma Cucina up
        command_close: /config/pytahoma Cucina down
        command_stop: /config/pytahoma Cucina stop
      salone:
        command_open: /config/pytahoma Salone up
        command_close: /config/pytahoma Salone down
        command_stop: /config/pytahoma Salone stop
      stanza_da_letto:
        command_open: /config/pytahoma 'Stanza da letto' up
        command_close: /config/pytahoma 'Stanza da letto' down
        command_stop: /config/pytahoma 'Stanza da letto' stop
      camera_irene:
        command_open: /config/pytahoma 'Camera Irene' up
        command_close: /config/pytahoma 'Camera Irene' down
        command_stop: /config/pytahoma 'Camera Irene' stop
      camera:
        command_open: /config/pytahoma Camera up
        command_close: /config/pytahoma Camera down
        command_stop: /config/pytahoma Camera stop
      cupola:
        command_open: /config/pytahoma Cupola up
        command_close: /config/pytahoma Cupola down
        command_stop: /config/pytahoma Cupola stop
      veranda:
        command_open: /config/pytahoma Veranda up
        command_close: /config/pytahoma Veranda down
        command_stop: /config/pytahoma Veranda stop

# Track the Sun and the Moon
sun:
sensor:
  - platform: moon

# HA bad logins
  - platform: command_line
    name: HA bad logins
    command: grep -sc 'Login attempt' /config/home-assistant.log
    scan_interval: 600

# Internet speed test
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
    hour:
      - 15
      - 23

# QNAP
  - platform: qnap
    host: 192.168.1.48
    username: admin
    password: !secret qnap_password
    verify_ssl: true
    monitored_conditions:
      - system_temp
      - cpu_usage
      - memory_percent_used
      - volume_size_free

# Particle photon Veranda
  - platform: mqtt
    name: Temperature Veranda
    state_topic: thlveranda
    value_template: '{{ value_json.temp }}'
    unit_of_measurement: '°C'

  - platform: mqtt
    name: Humidity Veranda
    state_topic: thlveranda
    value_template: '{{ value_json.humidity }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: Luminosity Veranda
    state_topic: thlveranda
    value_template: '{{ value_json.lux }}'
    unit_of_measurement: '%'

# WUnderground
  - platform: wunderground
    api_key: !secret wunderground_key
    pws_id: !secret wunderground_pws_id
    monitored_conditions:
      - weather_1d_metric
      - weather_1n_metric
      - weather_2d_metric
      - weather_2n_metric
      - temp_high_record_c
      - temp_high_1d_c
      - temp_c
      - feelslike_c
      - dewpoint_c
      - temp_low_1d_c
      - temp_low_record_c
      - relative_humidity
      - pressure_mb
      - pressure_trend
      - precip_today_metric
      - precip_1d
      - wind_kph
      - wind_gust_kph
      - wind_dir
      - alerts
