#
# LoPresti smart home - configuration file for Home Assistant
#
##############################################################

homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret ha_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret ha_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Zurich

# include all automation rules
#include automation.yaml

# debug mode
logger:
  default: debug

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  #ssl_certificate: /share/homes/admin/qnap/configBackup/nas.crt
  #ssl_key: /share/homes/admin/qnap/configBackup/nas.key

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables events recording on MySQL
#recorder:
#  db_url: sqlite:///share/CACHEDEV1_DATA/.qpkg/qnap-homeassistant/conf/hass.db
          #mysql+pymysql://homeass:homeass@192.168.1.31/homeass
#  exclude:
#    domains:
#      - automation
#      - weblink
#      - updater
#    entities:
#      - sun.sun   # Don't record sun data
#      - sensor.last_boot

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Text to speech
tts:
  platform: google


# Custom cloud services
#########################

# Pushbullet
notify:
  platform: pushbullet
  name: notify
  api_key: !secret pushbullet_api_key

# IFTTT
ifttt:
  key: !secret ifttt_key

# Track the Sun and the Moon
sun:
sensor:
  - platform: moon


# Home devices
#########################

# Network devices: this works with arp, which had
# to be copied from a Fedora 25 box as QNAP does not provide it.
device_tracker:
  - platform: nmap_tracker
    hosts:
    - 192.168.1.21   # Giu
    - 192.168.1.23   # Isa


# QNAP
  - platform: qnap
    host: 192.168.1.31
    username: admin
    password: !secret qnap_password
    verify_ssl: true
    monitored_conditions:
      - system_temp
      - cpu_usage
      - memory_percent_used

# Kodi player from QNAP/HybridDesk Station
#  - platform: kodi
#    host: 192.168.1.31

# Particle photon Veranda
  - platform: dweet
    name: Temperatura Veranda
    device: glp_photon_vth
    value_template: '{{ value_json.temp }}'
    unit_of_measurement: "°C"

# NetAtmo weather station
netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: glopresti@gmail.com
  password: !secret netatmo_password

# DLink camera
camera:
  - platform: generic
    name: Salone-Ingresso
    still_image_url: http://192.168.1.4/image.jpg
    username: admin
    password: !secret camera_password

# Onkyo amplifier - broken for now
media_player:
  - platform: onkyo
    host: 192.168.1.30
    name: Amplificatore
#    sources:
#      bd-dvd: 'BD/DVD'
#      pc: 'NAS'
#      tuner: 'Tuner'
#      video1: 'Cable TV'
#      video7: 'Aux'

# Edimax power socket
switch:
  - platform: edimax
    host: 192.168.1.40
    name: Luce Salone
    password: !secret edimax_password

# KIRA IR remote control
kira:
  remotes:
    - name: kira_remote
    - host: 192.168.1.100
    - port: 65432

# Somfy shutters + store + roof

# Orbit watering

# Wolf heating system

