#
# LoPresti smart home - configuration file for Home Assistant
#
##############################################################

# General HA configuration
############################

homeassistant:
  name: Casa
  # location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  # altitude above sea level in meters, impacts weather/sunrise data
  elevation: !secret ha_elevation
  unit_system: metric
  time_zone: Europe/Zurich
  # custom icons and friendly names go there
  customize: !include customizations.yaml

# include all layout/grouping
group: !include groups.yaml

# include all scenes
scene: !include scenes.yaml

# include all scripts
script: !include scripts.yaml

# the automation rules are split per area
automation:
  # Stato generale casa
  - !include automations/giorno.yaml
  - !include automations/giornoauto.yaml
  - !include automations/notte.yaml
  - !include automations/notteauto.yaml
  - !include automations/festa.yaml
  - !include automations/bad_logins.yaml
  # Cucu'
  - !include automations/cucu.yaml
  # Presa comandata lume
  - !include automations/lume_sera.yaml
  - !include automations/lume_rientro_serale.yaml
  - !include automations/lume_pioggia_on.yaml
  - !include automations/lume_pioggia_off.yaml
  # VerandaCam night mode
  - !include automations/verandacam_night.yaml
  # Media center
  - !include automations/cinemaon.yaml
  - !include automations/radio.yaml
  # Covers
  - !include automations/tendaveranda_open.yaml
  - !include automations/tendaveranda_close.yaml
  - !include automations/covers_pianoterra_close.yaml
  - !include automations/covers_pianoterra_sera.yaml
  - !include automations/cupola.yaml
  # Irrigazione
#  - !include automations/irrigazione.yaml

# Frontend helper components for automations
input_select:
  # Global home mode selector
  statocasa:
    name: Stato casa
    options:
      - Normale
      - Notte
      - Festa
    icon: mdi:home

  # Radio selector
  internet_radio:
    name: Radio
    options:
      - Scegli...
      - Radio Maria
      - Venezia Classica
    initial: Scegli...
    icon: mdi:radio

  # extra hidden control for the missing state of the Veranda (Somfy) curtain
  cover_veranda_state:
    options:
      - open
      - closed
    initial: closed

# Logging levels
logger:
  default: warning
  logs:
    homeassistant.components.device_tracker: critical
    homeassistant.components.camera: info
    homeassistant.components.automation: debug
    homeassistant.components.sensor.command_line: warning
    homeassistant.components.scene: info
    homeassistant.components.switch: info
    homeassistant.components.cover: info

# Enables the frontend
frontend:

# Enables the configuration tab
config:

# Login and SSL
http:
  api_password: !secret http_password
  base_url: !secret http_base_url
  ssl_certificate: /config/sslcert.crt
  ssl_key: /config/sslkey.key
  ip_ban_enabled: True
  login_attempts_threshold: 5
  trusted_networks:
    - 192.168.1.0/24

# Checks for available updates and reports used components
updater:
  include_used_components: True

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables events recording
recorder:
  exclude:
    domains:
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.moon
      - sensor.last_boot
      - sensor.igd_received_bytes
      - sensor.igd_sent_bytes
      - sensor.ha_warnings
      - sensor.ha_errors
      - sensor.dt_salonecam
      - sensor.dt_verandacam
      - sensor.dt_repeater
      - sensor.dt_printer
      - sensor.dt_iomegadisk
      - sensor.dt_sunrisetv
      - sensor.dt_chromecast
      - sensor.dt_ledcontroller
      - sensor.dt_ipad
      - sensor.dt_htc
      - sensor.dt_isamac
      - sensor.dt_glplap

# Displays graphs in the main frontend
history_graph:
  gr_temperature:
    name: Temperature
    entities:
      - sensor.netatmo_indoor_temperature
      - sensor.veranda_temperature
      - sensor.netatmo_outdoor_temperature
      - sensor.pws_feelslike_c
      - sensor.pws_temp_high_record_c
      - sensor.pws_temp_low_record_c
    hours_to_show: 36
    refresh: 600   # 10 minutes

# Enables support for tracking state changes over time -> to be replaced by grafana
history:

# View all events in a logbook
logbook:

# Zones
zone 1:
  name: CERN
  latitude: 46.232175
  longitude: 6.050528
  radius: 600

zone 2:
  name: !secret z2_name
  latitude: !secret z2_latitude
  longitude: !secret z2_longitude
  radius: 300

zone 3:
  name: !secret z3_name
  latitude: !secret z3_latitude
  longitude: !secret z3_longitude
  radius: 100

#zone 4:
#  name: !secret z4_name
#  latitude: !secret z4_latitude
#  longitude: !secret z4_longitude
#  radius: 10000

# Add a map with locations in the frontend
map:

# Useful links
weblink:
  entities:
    - name: Router
      url: http://192.168.1.1
    - name: QNAP administration
      url: !secret qnap_admin_link
    - name: Onkyo web interface
      url: http://192.168.1.30
    - name: VerandaCam administration
      url: http://192.168.1.21:8080
    - name: Printer administration
      url: http://192.168.1.50
    - name: Google Cloud Print
      url: https://www.google.com/cloudprint/#printers
    - name: IOMega disk administration
      url: http://192.168.1.32
    - name: WiFi Repeater administration
      url: http://192.168.1.32
    - name: NetAtmo station
      url: https://my.netatmo.com/app/station
    - name: WUnderground station
      url: !secret wunderground_link

panel_iframe:
  dashboard:
    title: Grafana Dashboard
    icon: mdi:view-dashboard
    url: !secret qnap_grafana_link
  homeass:
    title: Home Assistant Web
    icon: mdi:home-assistant
    url: https://home-assistant.io

# Custom cloud services
#########################

# Text to speech
tts:
  platform: google
  language: 'it'

# Pushbullet
notify me:
  platform: pushbullet
  name: notifyglp
  api_key: !secret pushbullet_api_key

# IFTTT
#ifttt:
#  key: !secret ifttt_key

# Connected devices
####################

# MQTT broker (mosquitto) running on the QNAP
mqtt:
  broker: 192.168.1.48
  client_id: homeass

# Track home devices
device_tracker:
  - platform: nmap_tracker
    interval_seconds: 60
    hosts:
    - 192.168.1.0/24

# Track mobile phones' locations
  - platform: gpslogger

# To get router statistics
upnp:
  port_mapping:

# NetAtmo weather station
netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_user
  password: !secret netatmo_password
  discovery: False

camera:
# DLink camera
  - platform: generic
    name: Salone-Cucina
    still_image_url: http://192.168.1.4/image.jpg
    username: admin
    password: !secret camera_password
#  - platform: mjpeg
#    mjpeg_url: http://192.168.1.4/video.cgi

# MotoG camera
android_ip_webcam:
  name: VerandaCam
  host: 192.168.1.21
  username: admin
  password: !secret camera_password
  sensors:
    - motion
    - light
  switches:
    - focus
    - torch
    - video_recording
    - night_vision

# Onkyo amplifier
media_player:
  - platform: onkyo
    host: 192.168.1.30
    name: Amplificatore Onkyo
    sources:
      video2: 'Cable TV'
      dvd: 'BD/DVD'
      video6: 'NAS'
      video3: 'ChromeCast'
      network: 'Network'
      aux1: 'Aux'
      #tuner: 'Tuner'
      #dlna: 'DLNA'
      #internet-radio: 'Radio'

# Google Chromecast
  - platform: cast
    host: 192.168.1.55

# Edimax power socket
switch:
  - platform: edimax
    host: 192.168.1.40
    name: Smartplug
    password: !secret edimax_password

# Commands to interface to KIRA
  - platform: command_line
    switches:
      kira_projector_power:
        command_on: /usr/bin/curl -X GET http://192.168.1.31/remote2.htm\?button020
        command_off: /usr/bin/curl -X GET http://192.168.1.31/remote2.htm\?button020
        value_template: '{{ value == "1" }}'
        friendly_name: KIRA Sony Projector
      #kira_dvd_power:
      #kira_tvdecoder_power:

# Somfy Tahoma for shutters/roof/store
tahoma:
  username: !secret somfy_user
  password: !secret somfy_password

cover:
  - platform: tahoma

light:
# LED for the home theater
  - platform: flux_led
    devices:
      192.168.1.56:
        name: LED Salone


# Sensors
##########

# Track the Sun and the Moon
sun:
sensor:
  - platform: moon

# The current Home Assistant version, to track upgrades history
  - platform: version

# HA-specific sensors
  - platform: command_line
    name: HA Config LoC
    command: "wc -l /config/*yaml /config/automations/* | grep total | awk '{print $1}'"
    scan_interval: 40000

  - platform: command_line
    name: HA Entities
    command: "grep -c '^ *-' /config/groups.yaml"
    scan_interval: 40000

  - platform: command_line
    name: HA Warnings
    command: "grep WARN /config/home-assistant.log | grep -cv grep"
    scan_interval: 600

  - platform: command_line
    name: HA Errors
    command: "grep ERROR /config/home-assistant.log | grep -cv grep"
    scan_interval: 600

# QNAP
  - platform: qnap
    host: 192.168.1.48
    username: admin
    password: !secret qnap_password
    verify_ssl: true
    monitored_conditions:
      - system_temp
      - cpu_usage
      - memory_percent_used
      - drive_smart_status
      - drive_temp
#     - volume_size_free

# Count of banned IPs because of failed login attempts
  - platform: command_line
    name: QNAP Banned IPs
    # /media is actually a mount of /mnt/HDA_ROOT/.logs!
    command: "grep -ac ban /media/notice.log"
    scan_interval: 600

# Free space (in GiB) from QNAP itself and the IOMega disk mounted on /mnt
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /config
      - type: disk_free
        arg: /mnt

# Internet speed test
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
    hour:
      - 7
      - 15
      - 23
    minute:
      - 15

# Particle photon Veranda
  - platform: mqtt
    name: Veranda Temperature
    state_topic: thlveranda
    value_template: '{{ value_json.temp }}'
    unit_of_measurement: '°C'

  - platform: mqtt
    name: Veranda Humidity
    state_topic: thlveranda
    value_template: '{{ value_json.humidity }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: Veranda Brightness
    state_topic: thlveranda
    value_template: '{{ value_json.lux }}'
    unit_of_measurement: '%'

# OwnTrack-related sensors
#  - platform: mqtt
#    state_topic: "owntracks/nova"
#    name: "Battery Nova"
#    unit_of_measurement: "%"
#    value_template: '{{ value_json.batt }}'

# NetAtmo weather station
  - platform: netatmo
    modules:
      Indoor:
        - temperature
        - humidity
        - pressure
        - co2
        - noise
      Outdoor:
        - temperature
        - humidity
        - min_temp
        - max_temp
        - battery_vp
      Terrace:
        - windangle
        - windstrength
        - gustangle
        - guststrength
        - battery_vp

# WUnderground on top of NetAtmo
  - platform: wunderground
    api_key: !secret wunderground_key
    pws_id: !secret wunderground_pws_id
    monitored_conditions:
      - weather_1d_metric
      - weather_1n_metric
#     - weather_2d_metric
#     - weather_2n_metric
      - temp_high_record_c
      - temp_high_1d_c
      - temp_c
      - feelslike_c
      - dewpoint_c
      - temp_low_1d_c
      - temp_low_record_c
      - relative_humidity
      - pressure_mb
      - pressure_trend
      - precip_today_metric
      - precip_1d
      - wind_kph
      - wind_gust_kph
      - wind_dir
      - alerts

# Dark Sky web service
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - precip_intensity
      - precip_probability
      - precip_intensity_max
      - cloud_cover

# TPG & SBB-CFF-FFS
# download data at https://opentransportdata.swiss/en/dataset
#  - platform: gtfs
#    name: Tram 18
#    origin: 8593026        # Meyrin village
#    destination: 8587437   # Carouge
#    data: sbb
#
#  - platform: gtfs
#    name: Treno
#    origin: 8501006        # Meyrin-Vernier
#    destination: 8501008   # Geneve Cornavin
#    data: sbb

# Templated sensors
#
# convert all the devices' states to online/offline
  - platform: template
    sensors:
      dt_ipad:
        friendly_name: iPad
        icon_template: mdi:tablet-ipad
        value_template: "{% if is_state('device_tracker.ipad', 'home') %}on{% else %}off{% endif %}"
      dt_htc:
        friendly_name: HTC
        icon_template: mdi:cellphone-android
        value_template: "{% if is_state('device_tracker.htc', 'home') %}on{% else %}off{% endif %}"
      dt_isamac:
        friendly_name: Mac Isa
        icon_template: mdi:laptop-mac
        value_template: "{% if is_state('device_tracker.isamac', 'home') %}on{% else %}off{% endif %}"
      dt_glplap:
        friendly_name: PC Giu
        icon_template: mdi:laptop-windows
        value_template: "{% if is_state('device_tracker.glplap', 'home') %}on{% else %}off{% endif %}"

      dt_edimaxswitch:
        friendly_name: Power Plug
        icon_template: mdi:power-plug
        value_template: "{% if is_state('device_tracker.edimaxswitch', 'home') %}on{% else %}off{% endif %}"
      dt_salonecam:
        friendly_name: SaloneCam
        icon_template: mdi:camera-front-variant
        value_template: "{% if is_state('device_tracker.salonecam', 'home') %}on{% else %}off{% endif %}"
      dt_verandacam:
        friendly_name: VerandaCam
        icon_template: mdi:camera-front-variant
        value_template: "{% if is_state('device_tracker.verandacam', 'home') %}on{% else %}off{% endif %}"
      dt_repeater:
        friendly_name: WiFi Repeater
        icon_template: mdi:access-point-network
        value_template: "{% if is_state('device_tracker.repeater', 'home') %}on{% else %}off{% endif %}"
      dt_printer:
        friendly_name: Printer
        icon_template: mdi:printer
        value_template: "{% if is_state('device_tracker.printer', 'home') %}on{% else %}off{% endif %}"
      dt_iomegadisk:
        friendly_name: IOMega Disk
        icon_template: mdi:harddisk
        value_template: "{% if is_state('device_tracker.iomegadisk', 'home') %}on{% else %}off{% endif %}"
      dt_sunrisetv:
        friendly_name: Sunrise TV
        icon_template: mdi:television
        value_template: "{% if is_state('device_tracker.sunrisetv', 'home') %}on{% else %}off{% endif %}"
      dt_onkyoamp:
        friendly_name: Onkyo
        icon_template: mdi:amplifier
        value_template: "{% if is_state('device_tracker.onkyoamp', 'home') %}on{% else %}off{% endif %}"
      dt_chromecast:
        friendly_name: ChromeCast
        icon_template: mdi:cast
        value_template: "{% if is_state('device_tracker.chromecast', 'home') %}on{% else %}off{% endif %}"
      dt_bddvd:
        friendly_name: BD/DVD
        icon_template: mdi:disk
        value_template: "{% if is_state('device_tracker.bddvd', 'home') %}on{% else %}off{% endif %}"
      dt_kira:
        friendly_name: KIRA
        icon_template: mdi:remote
        value_template: "{% if is_state('device_tracker.kira', 'home') %}on{% else %}off{% endif %}"
      dt_ledcontroller:
        friendly_name: LED Salone
        icon_template: mdi:led-strip
        value_template: "{% if is_state('device_tracker.ledcontroller', 'home') %}on{% else %}off{% endif %}"

# Group current, min, and max outdoor temperatures in one sensor
      netatmo_outdoor_minmaxtemperature:
        friendly_name: Outdoor Temperature
        icon_template: mdi:thermometer
        value_template: "{{ states.sensor.netatmo_outdoor_temperature.state }}°C ({{ states.sensor.netatmo_outdoor_min_temp.state }}°C ÷ {{ states.sensor.netatmo_outdoor_max_temp.state }}°C)"

# Disks free space
      naslopresti_free_space:
        friendly_name: QNAP Free Space
        icon_template: mdi:chart-pie
        unit_of_measurement: GiB
        value_template: "{{ states('sensor.disk_free_config')|int }}"
      iomega_free_space:
        friendly_name: IOMega Free Space
        icon_template: mdi:chart-pie
        unit_of_measurement: GiB
        value_template: "{{ states('sensor.disk_free_mnt')|int }}"

# Group QNAP SMART states
      naslopresti_smart_status:
        icon_template: mdi:harddisk
        friendly_name: 'QNAP Drives SMART Status'
        value_template: >
          {% if is_state('sensor.naslopresti_smart_status_drive_01', 'OK') and is_state('sensor.naslopresti_smart_status_drive_02', 'OK') %}
            OK
          {% else %}
            {{ states.sensor.naslopresti_smart_status_drive_01 }} & {{ states.sensor.naslopresti_smart_status_drive_02 }}
          {% endif %}

# Group QNAP disks temperatures
      naslopresti_drives_max_temperature:
        icon_template: mdi:thermometer
        friendly_name: 'QNAP Drives Temperature'
        unit_of_measurement: °C
        value_template: "{{ [states('sensor.naslopresti_temperature_drive_01')|int, states('sensor.naslopresti_temperature_drive_02')|int] | max }}"
