#
# LoPresti smart home - configuration file for Home Assistant
#
##############################################################

homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret ha_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret ha_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Zurich

# include all automation rules
#include automation.yaml

# debug mode
logger:
  default: debug

# Show links to resources in log and frontend
#$introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  #ssl_certificate: /share/homes/admin/qnap/configBackup/nas.crt
  #ssl_key: /share/homes/admin/qnap/configBackup/nas.key

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables events recording on MySQL
recorder:
  db_url: sqlite://
          #sqlite:///share/CACHEDEV1_DATA/.qpkg/qnap-homeassistant/conf/hass.db
          #mysql+pymysql://homeass:homeass@192.168.1.31/homeass
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun   # Don't record sun data
      - sensor.last_boot

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Text to speech
tts:
  platform: google


# Custom cloud services
#########################

# Pushbullet
notify:
  platform: pushbullet
  name: notify
  api_key: !secret pushbullet_api_key

# IFTTT
#ifttt:
#  key: 

# Track the Sun and the Moon
sun:
sensor:
  - platform: moon

# Home devices
#########################

# QNAP
  - platform: qnap
    host: 192.168.1.31
    username: admin
    password: !secret qnap_password
    verify_ssl: true
    monitored_conditions:
      - system_temp
      - cpu_usage
      - memory_percent_used

# Kodi player from QNAP/HybridDesk Station
  - platform: kodi
    host: 192.168.1.31

# Mobile phones presence
device_tracker:
  - platform: ping
    interval_seconds: 10
    consider_home: 180
    track_new_devices: yes
    hosts:
      hostone: 192.168.1.31
      #F8:CF:C5:AA:CC:A7  Giu
      #00:EE:BD:91:F7:CE  Isa

# NetAtmo weather station
netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: glopresti@gmail.com
  password: !secret netatmo_password
  modules:
    indoor:
      - temperature
      - humidity
      - noise
      - pressure
      - co2
    outdoor:
      - temperature
      - humidity
    veranda:
      - wind

# DLink camera
camera:
  - platform: generic
    name: LoPrestiCam
    still_image_url: http://192.168.1.4/image.jpg
    username: admin
    password: !secret camera_password

# Onkyo amplifier
media_player:
  - platform: onkyo
    host: 192.168.1.30
    name: Amplificatore Onkyo
    sources:
      bd-dvd: 'BD-DVD'
      pc: 'NAS'
      tuner: 'Tuner'
      video1: 'CableTV'
      video7: 'Aux'

# Edimax power socket
switch:
  - platform: edimax
    host: 192.168.1.40
    name: EdimaxPlug
    password: !secret edimax_password

# Particle photon Veranda

# Somfy shutters + store

# Orbit sprinkler

# Wolf heating system
