#
# LoPresti smart home - configuration file for Home Assistant
#
##############################################################

homeassistant:
  # name of the location where Home Assistant is running
  name: !secret ha_name
  # location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  # altitude above sea level in meters, impacts weather/sunrise data
  elevation: !secret ha_elevation
  unit_system: metric
  time_zone: Europe/Zurich
#  customize:    # not working -> try with groups
#    sensor_netatmo_indoor_wifi:
#      hidden: True
#    sensor_netatmo_outdoor_radio:
#      hidden: True
#    sensor_netatmo_veranda_radio:
#      hidden: True

# include all layout/grouping
group: !include groups.yaml

# include all automation rules
automation: !include automations.yaml

logger:
  default: warn
  logs:
    homeassistant.components.device_tracker: critical
    homeassistant.components.camera: info
    homeassistant.components.automation: debug
    homeassistant.components.sensor: debug
    homeassistant.components.sensor.command_line: warning
    homeassistant.components.scene: debug
    homeassistant.components.switch: info

# Enables the frontend
frontend:

http:
  api_password: !secret http_password
  ssl_certificate: /config/myhost.crt
  ssl_key: /config/myhost.key
  ip_ban_enabled: True
  login_attempts_threshold: 5
  trusted_networks:
    - 192.168.0.0/24

# Checks for available updates
updater:
  include_used_components: true

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables events recording
recorder:
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun   # Don't record Sun/Moon data
      - sensor.moon
      - sensor.last_boot

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# embedded MQTT broker
mqtt:
  embedded:
    listeners:
      websock:
        bind: 0.0.0.0:8883

# Text to speech
tts:
  platform: google

# Useful links
weblink:
  entities:
    - name: Router
      url: http://192.168.1.1
    - name: Amplificatore Onkyo
      url: http://192.168.1.30
    - name: QNAP
      url: http://naslopresti:8080
    - name: QNAP remote
      url: https://lopresti.myqnapcloud.com
    - name: NetAtmo
      url: https://my.netatmo.com/app/station
    - name: Somfy Tahoma
      url: https://www.tahomalink.com

# Custom cloud services
#########################

# Pushbullet
notify:
  platform: pushbullet
  name: hass
  api_key: !secret pushbullet_api_key

# IFTTT
ifttt:
  key: !secret ifttt_key

# Sensors and devices
#########################

# Track the Sun and the Moon
sun:
sensor:
  - platform: moon

# HA bad logins
  - platform: command_line
    name: badlogins
    command: grep -c 'Login attempt' /config/home-assistant.log

# QNAP
  - platform: qnap
    host: 192.168.1.48
    username: admin
    password: !secret qnap_password
    verify_ssl: true
    monitored_conditions:
      - system_temp
      - cpu_usage
      - memory_percent_used

# Kodi player from QNAP/HybridDesk Station
#  - platform: kodi
#    host: 192.168.1.48

# Particle photon Veranda
  - platform: dweet
    name: Temperature Veranda
    device: glp_photon_vth
    value_template: '{{ value_json.temp }}'
    unit_of_measurement: "°C"

  - platform: dweet
    name: Humidity Veranda
    device: glp_photon_vth
    value_template: '{{ value_json.hum }}'
    unit_of_measurement: "%"

# NetAtmo weather station
  - platform: netatmo
    modules:
      Indoor:
        - temperature
        - humidity
        - pressure
        - co2
        - noise
      Outdoor:
        - temperature
        - humidity
        - battery_vp
      Veranda:
        - windangle
        - gustangle
        - guststrength
        - battery_vp

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: glopresti@gmail.com
  password: !secret netatmo_password

# Track mobile phones
device_tracker:
  - platform: nmap_tracker
    home_interval: 10   # minutes
    hosts:
    - 192.168.1.51   # Giu
    - 192.168.1.52   # Isa

# DLink camera
camera:
  - platform: generic
    name: Salone-Ingresso
    still_image_url: http://192.168.1.4/image.jpg
    username: admin
    password: !secret camera_password

# MotoG camera
  - platform: generic
    name: Veranda
    still_image_url: http://192.168.1.21:8080/shot.jpg
    username: admin
    password: !secret camera_password

# Onkyo amplifier
media_player:
  - platform: onkyo
    host: 192.168.1.30
    name: Amplificatore
    sources:
      dvd: 'BD/DVD'
      video2: 'Cable TV'
      video6: 'NAS'
      network: 'Network'
      aux1: 'Aux'
      #tuner: 'Tuner'
      #dlna: 'DLNA'
      #internet-radio: 'Radio'

# Edimax power socket
switch:
  - platform: edimax
    host: 192.168.1.40
    name: Luce Salone
    password: !secret edimax_password

# KIRA IR remote control
kira:
  remotes:
    - name: kira_remote
      host: 192.168.1.31

# Somfy Tahoma for shutters/roof/store
cover:
  - platform: command_line
    covers:
      cucina:
        command_open: /config/pytahoma Cucina up
        command_close: /config/pytahoma Cucina down
        command_stop: /config/pytahoma Cucina stop
      salone:
        command_open: /config/pytahoma Salone up
        command_close: /config/pytahoma Salone down
        command_stop: /config/pytahoma Salone stop
      stanza_da_letto:
        command_open: /config/pytahoma 'Stanza da letto' up
        command_close: /config/pytahoma 'Stanza da letto' down
        command_stop: /config/pytahoma 'Stanza da letto' stop
      camera_irene:
        command_open: /config/pytahoma 'Camera Irene' up
        command_close: /config/pytahoma 'Camera Irene' down
        command_stop: /config/pytahoma 'Camera Irene' stop
      camera:
        command_open: /config/pytahoma Camera up
        command_close: /config/pytahoma Camera down
        command_stop: /config/pytahoma Camera stop
      cupola:
        command_open: /config/pytahoma Cupola up
        command_close: /config/pytahoma Cupola down
        command_stop: /config/pytahoma Cupola stop
      veranda:
        command_open: /config/pytahoma Veranda up
        command_close: /config/pytahoma Veranda down
        command_stop: /config/pytahoma Veranda stop

# Wolf heating system
