#
# LoPresti smart home - configuration file for Home Assistant
#
##############################################################

# General HA configuration
############################

homeassistant:
  name: !secret ha_name
  # location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  # altitude above sea level in meters, impacts weather/sunrise data
  elevation: !secret ha_elevation
  unit_system: metric
  time_zone: Europe/Zurich
  # all custom icons and friendly names go here
  customize:
    sensor.ha_bad_logins:
      icon: mdi:account-key
    sensor.humidity_veranda:
      icon: mdi:water-percent
    sensor.luminosity_veranda:
      icon: mdi:lightbulb-on-outline
    sensor.pws_wind_dir:
      icon: mdi:compass
    cover.cupola:
      icon: mdi:arrange-send-backward
    scene.cinema:
      icon: mdi:projector
    switch.smartplug:
      friendly_name: 'Lume'
    sensor.pws_temp_high_record_c:
      friendly_name: 'High Temperature record'
    sensor.pws_temp_low_record_c:
      friendly_name: 'Low Temperature record'
    sensor.pws_weather_1d_metric:
      friendly_name: 'Today'
    sensor.pws_weather_1n_metric:
      friendly_name: 'Tonight'
    sensor.naslopresti_cpu_usage:
      friendly_name: 'QNAP CPU usage'
    sensor.naslopresti_memory_usage:
      friendly_name: 'QNAP RAM usage'
    sensor.naslopresti_system_temperature:
      friendly_name: 'QNAP Temperature'
    sensor.naslopresti_free_space_data:
      friendly_name: 'QNAP Free space'

# include all layout/grouping
group: !include groups.yaml

# include all automation rules
automation: !include automations.yaml

# include all scenes
scene: !include scenes.yaml

logger:
  default: warn
  logs:
    homeassistant.components.device_tracker: critical
    homeassistant.components.camera: info
    homeassistant.components.automation: debug
    homeassistant.components.sensor: debug
    homeassistant.components.sensor.command_line: warn
    homeassistant.components.scene: debug
    homeassistant.components.switch: info
    homeassistant.components.cover: info

# Enables the frontend
frontend:

# Enables the configuration tab
config:

# Login and SSL
http:
  api_password: !secret http_password
  base_url: !secret http_base_url
  ssl_certificate: /config/myhost.crt
  ssl_key: /config/myhost.key
  ip_ban_enabled: True
  login_attempts_threshold: 5
  trusted_networks:
    - 192.168.0.0/24

# Checks for available updates
updater:
  include_used_components: True

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables events recording
recorder:
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun   # Don't record Sun/Moon data
      - sensor.moon
      - sensor.last_boot

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Text to speech
tts:
  platform: google
  language: 'it'

# Zones
zone 1:
  name: CERN
  latitude: 46.232175
  longitude: 6.050528
  radius: 600

# Useful links
weblink:
  entities:
    - name: QNAP
      url: https://lopresti.myqnapcloud.com
    - name: Onkyo (local)
      url: http://192.168.1.30
    - name: NetAtmo station
      url: https://my.netatmo.com/app/station
    - name: Somfy Tahoma
      url: https://www.tahomalink.com

panel_iframe:
  router:
    title: Router
    url: https://sunrise.box

# Custom cloud services
#########################

# Pushbullet
notify:
  platform: pushbullet
  name: hass
  api_key: !secret pushbullet_api_key

# IFTTT
ifttt:
  key: !secret ifttt_key

# Sensors and devices
#########################

# MQTT broker (mosquitto) running on the QNAP
mqtt:
  broker: 192.168.1.48

# Track mobile phones
device_tracker:
  - platform: nmap_tracker
    home_interval: 10   # minutes
    hosts:
    - 192.168.1.51   # Giu
    - 192.168.1.52   # Isa

  - platform: owntracks

# NetAtmo weather station
netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: glopresti@gmail.com
  password: !secret netatmo_password
  discovery: False

# DLink camera
camera:
  - platform: generic
    name: Salone-Ingresso
    still_image_url: http://192.168.1.4/image.jpg
    username: admin
    password: !secret camera_password

# MotoG camera
  - platform: android_ip_webcam
    host: 192.168.1.21
    name: Veranda
#    still_image_url: http://192.168.1.21:8080/shot.jpg
#    username: admin
#    password: !secret camera_password

# Onkyo amplifier
media_player:
  - platform: onkyo
    host: 192.168.1.30
    name: Amplificatore
    sources:
      dvd: 'BD/DVD'
      video2: 'Cable TV'
      video6: 'NAS'
      network: 'Network'
      aux1: 'Aux'
      #tuner: 'Tuner'
      #dlna: 'DLNA'
      #internet-radio: 'Radio'

# Kodi player in QNAP/HybridDesk Station
  - platform: kodi
    name: Kodi player in QNAP
    host: 192.168.1.48

# Edimax power socket
switch:
  - platform: edimax
    host: 192.168.1.40
    name: Smartplug
    password: !secret edimax_password

# KIRA IR remote control
kira:
  remotes:
    - name: kira_remote
      host: 192.168.1.31

# Somfy Tahoma for shutters/roof/store
cover:
  - platform: somfytahoma
    username: !secret somfy_user
    password: !secret somfy_password

# Track the Sun and the Moon
sun:
sensor:
  - platform: moon

# HA bad logins
  - platform: command_line
    name: HA bad logins
    command: grep -sc 'Login attempt' /config/home-assistant.log
    scan_interval: 600

# Internet speed test
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
    hour:
      - 15
      - 23

# QNAP
  - platform: qnap
    host: 192.168.1.48
    username: admin
    password: !secret qnap_password
    verify_ssl: true
    monitored_conditions:
      - system_temp
      - cpu_usage
      - memory_percent_used
      - volume_size_free

# Particle photon Veranda
  - platform: mqtt
    name: Temperature Veranda
    state_topic: thlveranda
    value_template: '{{ value_json.temp }}'
    unit_of_measurement: '°C'

  - platform: mqtt
    name: Humidity Veranda
    state_topic: thlveranda
    value_template: '{{ value_json.humidity }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: Luminosity Veranda
    state_topic: thlveranda
    value_template: '{{ value_json.lux }}'
    unit_of_measurement: '%'

# NetAtmo weather station
  - platform: netatmo
    station: Meyrin Village
    modules:
      Indoor:
        - temperature
        - humidity
        - pressure
        - co2
        - noise
      Outdoor:
        - temperature
        - humidity
        - min_temp
        - max_temp
        - battery_vp
      Terrace:
        - windangle
        - windstrength
        - gustangle
        - guststrength
        - battery_vp

# WUnderground
  - platform: wunderground
    api_key: !secret wunderground_key
    monitored_conditions:
      - weather_1d_metric
      - weather_1n_metric
      - weather_2d_metric
      - weather_2n_metric
      - temp_high_record_c
      - temp_high_1d_c
      - temp_c
      - feelslike_c
      - dewpoint_c
      - temp_low_1d_c
      - temp_low_record_c
      - relative_humidity
      - pressure_mb
      - pressure_trend
      - precip_today_metric
      - precip_1d
      - wind_kph
      - wind_gust_kph
      - wind_dir
      - alerts
