#
# LoPresti smart home - automation configuration for Home Assistant
#
####################################################################

# vai in modalita' Allarme se non c'e' nessuno per almeno 20 minuti
alias: 'Modo allarme automatico'
initial_state: True
trigger:
  platform: state
  entity_id: binary_sensor.presence
  to: 'off'
  for:
    minutes: 20

condition:
  - condition: template      # we must not already be in alarm mode
    value_template: "{{ states.input_select.statocasa.state != 'Allarme' }}"

action:
  - service: input_select.select_option
    data:
      entity_id: input_select.statocasa
      option: 'Allarme'
