#
# LoPresti smart home - automation configuration for Home Assistant
#
####################################################################

alias: 'Cinema setup'
initial_state: True
trigger:
  platform: event
  event_type: call_service
  event_data:
    service_data:
      entity_id: [scene.cinema]
    domain: scene
    service: turn_on

action:
  - service: tts.google_say
    entity_id: media_player.chromecast
    data:
      message: "Il cinema e' pronto!"
