#
# LoPresti smart home - automation configuration for Home Assistant
#
####################################################################

# chiudi salone e cucina se nessuno in casa & ora = 11.00
alias: 'Chiudi serrande simula presenza'

trigger:
  platform: time
  at: '11:00'

condition: state
  entity_id: group.famiglia
  state: 'not home'

action:
  - service: homeassistant.close
    entity_id: cover.cucina
  - service: homeassistant.close
    entity_id: cover.salone
