#
# LoPresti smart home - automation configuration for Home Assistant
#
####################################################################

# chiudi la cucina se nessuno in casa & ora ~= 11 o 14.30 in un range di 20 minuti
alias: 'Chiudi serrande simula presenza'
initial_state: True
trigger:
  - platform: time
    at: '10:50:00'
  - platform: time
    at: '14:15:00'

condition:
  - condition: state
    entity_id: input_boolean.presence
    state: 'off'

action:
  - delay: '{{ "00:" ~ ((range(0, 20) | random) | int)  ~ ":00" }}'
  - service: scene.turn_on
    entity_id: scene.mattina_assenza
