#
# LoPresti smart home - automation configuration for Home Assistant
#
####################################################################

# chiudi la cucina se nessuno in casa & ora ~= 11.00 in un range di 40 minuti
alias: 'Chiudi serrande simula presenza'
initial_state: True
trigger:
  platform: time
  hours: 10
  minutes: 45
  seconds: 00

condition:
  - condition: state
    entity_id: group.famiglia
    state: 'not_home'
  - condition: state
    entity_id: group.portables
    state: 'off'

action:
  - delay: '{{ "00:" ~ ((range(5, 45) | random) | int)  ~ ":00" }}'
  - service: cover.stop_cover
    entity_id: cover.cucina
