#
# LoPresti smart home - automation configuration for Home Assistant
#
####################################################################

# chiudi salone e cucina la sera 45' dopo il tramonto (per l'inverno)
alias: 'Chiudi serrande piano terra di sera'
initial_state: True
trigger:
  platform: sun
  event: sunset
  offset: "00:45:00"

condition:
  - condition: template      # we must be in normal/alarm mode
    value_template: >-
       {{ states.input_select.statocasa.state == 'Normale' or
          states.input_select.statocasa.state == 'Allarme'
       }}

action:
  - service: cover.stop_cover
    entity_id: cover.cucina
  - service: cover.close_cover
    entity_id: cover.salone
