#
# LoPresti smart home - automation configuration for Home Assistant
#
####################################################################

# chiudi salone e cucina la sera dopo il tramonto (per l'inverno)
# e se c'e' qualcuno accendi i LED
alias: 'Chiudi serrande piano terra di sera'
initial_state: True

trigger:
  platform: numeric_state
  entity_id: sun.sun
  value_template: "{{ state.attributes.elevation }}"
  below: -4.5

condition:
  - condition: template          # we must be in normal mode
    value_template: >-
       {{ states.input_select.statocasa.state == 'Normale' }}
  - condition: numeric_state     # se c'e' caldo lascia aperto
    entity_id: sensor.netatmo_indoor_temperature
    below: 27

action:
  - service: scene.turn_on
    entity_id: scene.sera
  - service: homeassistant.turn_on
    data_template:
      entity_id: >-
        {% if is_state('input_boolean.presence', 'on') %}
          light.led_salone
        {% endif %}
