#
# LoPresti smart home - automation configuration for Home Assistant
#
# Cucu' - switch on the amplifier as it has some inertia
# to get online ...
####################################################################

alias: CucuPre
trigger:
  - platform: time
    minutes: 59
    seconds: 45
  - platform: time
    minutes: 29
    seconds: 45

condition:
  - condition: time
    after: '07:50:00'
    before: '22:10:00'
  - condition: state
    entity_id: group.famiglia
    state: 'home'
  - condition: template
    value_template: >
      {% if is_state('media_player.amplificatore_onkyo', 'on') %}
        false
      {% else %}
        true
      {% endif %}

action:
  - service: media_player.turn_on
    entity_id: media_player.chromecast

#  - service: media_player.volume_set
#    entity_id: media_player.chromecast
#    data:
#      volume_level: 0.6       # 60% of the main amplifier volume