#
# LoPresti smart home - automation configuration for Home Assistant
#
# Cucù
# credits to CCOSTAN@github
####################################################################

alias: 'Orologio a cucù'
trigger:
  - platform: time
    minutes: 59
    seconds: 53
  - platform: time
    minutes: 29
    seconds: 53

condition:
  - condition: time
    after: '08:10:00'
    before: '22:10:00'
  - condition: template      # context: not during night, only if Giu is home
    value_template: >-
        {{ not is_state('input_select.statocasa', 'Notte') and
             (is_state('device_tracker.giu_nova', 'home') or
              is_state('sensor.geo_giu_nova', 'Home'))
        }}
  - condition: template      # check the amplifier, the TV decoder, and the BD/DVD
    value_template: >-
        {{ is_state('media_player.amplificatore_onkyo', 'off') and
           is_state('media_player.chromecast', 'off') and
           is_state('binary_sensor.dt_sunrisetv', 'off') and
           is_state('binary_sensor.dt_bddvd', 'off')
        }}

action:
  - service: media_player.turn_on
    entity_id: media_player.chromecast

  - service: media_player.volume_set
    entity_id: media_player.chromecast
    data:
      volume_level: 0.60       # 60% of the main amplifier volume

  - service: media_player.turn_on
    entity_id: media_player.amplificatore_onkyo

  - delay: '00:00:07'

  - service: media_player.play_media
    data_template:
      entity_id: media_player.chromecast
      media_content_id: >
        {% if now().strftime("%M")|int == 30 %}
        https://raw.githubusercontent.com/glpatcern/domotica/master/homeass/resources/cuckoo-clock-01.wav
        {% else %}
        https://raw.githubusercontent.com/glpatcern/domotica/master/homeass/resources/cuckoo-clock-{{now().strftime("%I")}}.wav
        {% endif %}
      media_content_type: audio/mp4

  - delay: '00:00:15'

  - service: media_player.turn_off
    entity_id: media_player.amplificatore_onkyo

  - service: media_player.turn_off
    entity_id: media_player.chromecast
