# Cucu'
# credits to CCOSTAN@github
###################################

alias: Cucu
trigger:
  - platform: time
    minutes: 00
    seconds: 00
  - platform: time
    minutes: 30
    seconds: 00

condition:
  - condition: time
    after: '07:50:00'
    before: '22:10:00'
  - condition: state
    entity_id: group.famiglia
    state: 'home'
  - condition: template
    value_template: >
      {% if is_state('media_player.amplificatore', 'playing') %}
        false
      {% else %}
        true
      {% endif %}

action:
  - service: media_player.turn_on
    entity_id: media_player.amplificatore

  - service: media_player.volume_set
    entity_id: media_player.amplificatore
    data:
      volume_level: 20

  - service: media_player.play_media
    data_template:
      entity_id: media_player.amplificatore
      media_content_id: >
        {% if now().strftime("%M")|int == 30 %}
        https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/sounds/cuckoo-clock-01.wav
        {% else %}
        https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/sounds/cuckoo-clock-{{now().strftime("%I")}}.wav
        {% endif %}
      media_content_type: audio/mp4
