#
# LoPresti smart home - automation configuration for Home Assistant
#
# Apri cupola per ventilare se temperatura interna > 24C,
# non piove e siamo in estate
####################################################################

alias: 'Apri cupola se fa caldo'

trigger:
  # check every 15 minutes
  platform: time
  minutes: '/15'
  seconds: 00

condition:
  - condition: time
    after: '08:10'
    before: '23:00'
  - condition: template
    value_template: '{{ now().month > 4 and (now().month < 10 or (now().month == 10 and now().day < 15)) }}'
  - condition: template
    value_template: '{{ states.cover.cupola.attributes.current_position < 100 }}'
  - condition: numeric_state
    entity_id: sensor.netatmo_indoor_temperature
    above: 24
  - condition: numeric_state
    entity_id: sensor.dark_sky_precip_intensity
    below: 0.2
  - condition: template      # anything but 'Notte' is OK
    value_template: "{{ states.input_select.statocasa.state != 'Notte' }}"

action:
  - service: cover.open_cover
    entity_id: cover.cupola
