#
# LoPresti smart home - automation configuration for Home Assistant
#
# Apri cupola per ventilare se temperatura interna > 25C
####################################################################

alias: 'Apri cupola se fa caldo'

trigger:
  # check every 10 minutes
  platform: time
  minutes: '/10'
  seconds: 00

condition:
  - condition: time
    after: '08:10'
    before: '23:30'
  - condition: numeric_state
    entity_id: sensor.netatmo_indoor_temperature
    above: 25
  - condition: template      # anything but 'Notte' is OK
    value_template: "{{ states.input_select.statocasa.state != 'Notte' }}"

action:
  - service: cover.open_cover
    entity_id: cover.cupola
