#
# LoPresti smart home - automation configuration for Home Assistant
#
# Apri cupola per ventilare se non piove e temp. interna > 24C
# in estate, o > 25C il resto dell'anno
# la cupola si chiude autonomamente se inizia a piovere: questo
# e' usato dal sensore 'rain' nella configurazione principale
####################################################################

alias: 'Apri cupola se fa caldo'

trigger:
  # check every 15 minutes
  platform: time
  minutes: '/15'

condition:
  - condition: template      #  this to adapt the temperature threshold to the summer time
    value_template: '{{ states.sensor.netatmo_indoor_temperature.state|int >= 25 - (now().month > 4 and now().month < 10)|int }}'
  - condition: template      # anything but 'Notte' is OK
    value_template: "{{ states.input_select.statocasa.state != 'Notte' }}"
  - condition: template
    value_template: '{{ states.cover.cupola.attributes.current_position < 100 }}'
  - condition: numeric_state
    entity_id: sensor.dark_sky_precip_intensity
    below: 0.2

action:
  - service: cover.open_cover
    entity_id: cover.cupola
