#
# LoPresti smart home - automation configuration for Home Assistant
#
# Party mode
####################################################################

alias: 'Modo festa'
initial_state: True
trigger:
  platform: state
  entity_id: input_select.statocasa

condition:
  - condition: state
    entity_id: input_select.statocasa
    state: 'Festa'

action:
  - service: script.turn_on
    entity_id: script.partymode
