#
# LoPresti smart home - automation configuration for Home Assistant
#
####################################################################

# Alle 8 torna in modalita' normale e metti webcam in modo giorno
alias: 'Modo giorno automatico'
initial_state: True
trigger:
# not using sunrise because homeassistant may be shut off...
  - platform: time
    hours: 08
    minutes: 00
    seconds: 00

condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri

action:
  - service: input_select.select_option
    data:
      entity_id: input_select.statocasa
      option: 'Normale'
