#
# LoPresti smart home - automation configuration for Home Assistant
#
####################################################################

# Di prima mattina vai in modalita' normale
alias: 'Modo giorno automatico'
initial_state: True
trigger:
  - platform: time
    at: "07:40:00"
  - platform: time
    at: "08:00:00"

condition:
  - condition: template
    value_template: >-
      {{ is_state('binary_sensor.workday_sensor', 'on') and now().hour == 7 or
         is_state('binary_sensor.workday_sensor', 'off') and now().hour == 8
      }}

action:
  - service: input_select.select_option
    data:
      entity_id: input_select.statocasa
      option: 'Normale'
