#
# LoPresti smart home - automation configuration for Home Assistant
#
####################################################################

# Alle 8 o alle 9 vai in modalita' normale
alias: 'Modo giorno automatico'
initial_state: True
trigger:
  - platform: time
    hours: 08
    minutes: 00
    seconds: 00
  - platform: time
    hours: 09
    minutes: 00
    seconds: 00

condition:
  - condition: template
    value_template: >-
      {{ is_state('binary_sensor.workday_sensor', 'on') and now().hour == 8 or
         is_state('binary_sensor.workday_sensor', 'off') and now().hour == 9
      }}

action:
  - service: input_select.select_option
    data:
      entity_id: input_select.statocasa
      option: 'Normale'
