#
# LoPresti smart home - automation configuration for Home Assistant
#
####################################################################

# spegni se nessuno in casa & ora = 23.00
alias: 'Lume simula presenza off'

trigger:
  platform: time
  at: '23:00'

condition:
  - condition: state
    entity_id: group.famiglia
    state: 'not home'

action:
  service: homeassistant.turn_off
  entity_id: switch.smartplug
