#
# LoPresti smart home - automation configuration for Home Assistant
#
####################################################################

# accendi lume al tramonto
alias: 'Lume di sera'

trigger:
  platform: numeric_state
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
  below: 4
  above: 3.5

condition:
  - condition: time
    after: "12:00:00"
  - condition: time
    before: "20:00:00"

action:
  - service: homeassistant.turn_on
    entity_id: switch.smartplug
