#
# LoPresti smart home - automation configuration for Home Assistant
#
####################################################################

# accendi luce 15' dopo il tramonto e metti webcam in modo notte
alias: 'Lume e VerandaCam di sera'
initial_state: True
trigger:
  platform: sun
  event: sunset
  offset: "+00:15:00"

action:
  - service: homeassistant.turn_on
    entity_id: switch.smartplug
  - service: homeassistant.turn_on
    entity_id: switch.verandacam_night_vision
