#
# LoPresti smart home - automation configuration for Home Assistant
#
####################################################################

# accendi lume al tramonto
alias: 'Lume di sera'
initial_state: True
trigger:
  platform: sun
  event: sunset
  offset: "-00:20:00"

condition:
  - condition: state
    entity_id: binary_sensor.presence
    state: 'on'

action:
  - service: homeassistant.turn_on
    entity_id: switch.smartplug
