#
# LoPresti smart home - automation configuration for Home Assistant
#
####################################################################

# accendi lume al tramonto
alias: 'Lume di sera'
initial_state: True
trigger:
  platform: sun
  event: sunset
  offset: "-00:10:00"

action:
  - service: homeassistant.turn_on
    entity_id: switch.smartplug
