#
# LoPresti smart home - automation configuration for Home Assistant
#
# Accendi il lume se qualcuno rientra la sera
####################################################################

alias: 'Lume rientro serale'
trigger:
  - platform: state
    entity_id: group.famiglia
    from: 'not_home'
    to: 'home'

condition:
  - condition: sun
    after: sunset

  - condition: state
    entity_id: switch.smartplug
    state: 'off'

action:
  - service: homeassistant.turn_on
    entity_id: switch.smartplug

# To switch it off after a delay:
# - delay: "00:10:00"
# - service: homeassistant.turn_off
#   entity_id: switch.smartplug

# Also, check the following for automatic switch off after 20':
# https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/automation/System/watchdog_light.yaml

