#
# LoPresti smart home - automation configuration for Home Assistant
#
# Notifica se qualcuno rientra, evitando notifiche ridondanti
####################################################################

alias: 'Notifica rientri'
trigger:
  - platform: state
    entity_id: device_tracker.isa_mobile
    to: 'home'
  - platform: state
    entity_id: device_tracker.isa_mobile
    to: 'Casa Fe'
  - platform: state
    entity_id: binary_sensor.presence
    from: 'off'
    to: 'on'

condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: device_tracker.isa_mobile
        state: 'Casa Fe'
      - condition: state
        entity_id: device_tracker.giu_mobile
        state: 'not_home'

action:
  - service: notify.notifyglp
    data_template:
      message: "Qualcuno sta rientrando a casa"
