#
# LoPresti smart home - automation configuration for Home Assistant
#
# Auto night mode
####################################################################

alias: 'Modo notte automatico'
trigger:
  - platform: time
    at: "22:15:00"

condition:
  - condition: template      # this is to express that anything but 'Festa' is OK
    value_template: >
      {% if is_state("input_select.statocasa", "Festa") %}
        false
      {% else %}
        true
      {% endif %}
  - condition: numeric_state    # se c'e' caldo lascia tutto aperto
    entity_id: sensor.netatmo_indoor_temperature
    below: 27

action:
  - delay: '{{ "00:" ~ ((range(1, 10) | random) | int)  ~ ":00" }}'   # aggiunge un ritardo random
  - service: input_select.select_option
    data:
      entity_id: input_select.statocasa
      option: 'Notte'
  - service: input_select.select_option
    data:
      entity_id: input_select.cover_veranda_state
      option: 'closed'
