#
# LoPresti smart home - automation configuration for Home Assistant
#
# Notifica se qualcuno rientra + accendi lume se e' sera
# o apri serranda cucina se e' giorno
####################################################################

alias: 'Notifica rientro'
trigger:
  - platform: state
    entity_id: binary_sensor.presence
    from: 'off'
    to: 'on'

condition:
  - condition: state
    entity_id: input_boolean.presence
    state: 'off'

action:
  - service: notify.notifyglp
    data_template:
      message: "Qualcuno sta rientrando a casa"

  - service: homeassistant.turn_on
    entity_id: input_boolean.presence

  - service: homeassistant.turn_on
    data_template:
      entity_id: >-
        {% if is_state('sun.sun', 'below_horizon') %}
          switch.smartplug
        {% endif %}

  - service: homeassistant.turn_on
    data_template:
      entity_id: >-
        {% if is_state('sun.sun', 'below_horizon') and now().hour < 23 %}
          light.led_salone
        {% endif %}

  - service: cover.open_cover
    data_template:
      entity_id: >-
        {% if is_state('sun.sun', 'above_horizon') and now().hour < 18 %}
          cover.cucina
        {% endif %}

# To switch it off after a delay:
# - delay: "00:10:00"
# - service: homeassistant.turn_off
#   entity_id: switch.smartplug

# Also, check the following for automatic switch off after 20':
# https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/automation/System/watchdog_light.yaml
