#
# LoPresti smart home - automation configuration for Home Assistant
#
# alza tenda se vento > 28 km/h e invia notifica
####################################################################

alias: 'Chiudi tenda veranda per vento'
initial_state: True
trigger:
  - platform: numeric_state
    entity_id: sensor.netatmo_terrace_gust_strength
    above: 17

condition:
  - condition: state
    entity_id: input_select.cover_veranda_state
    state: 'open'

action:
  - service: cover.open_cover
    entity_id: cover.veranda
  - service: input_select.select_option
    data:
      entity_id: input_select.cover_veranda_state
      option: 'closed'
  - service: notify.notifyglp
    data_template:
      message: "Tenda veranda chiusa, raffiche di {{ states.sensor.netatmo_terrace_gust_strength.state }} km/h"
