#
# LoPresti smart home - automation configuration for Home Assistant
#
# alza tenda se piove o fa fresco + invia notifica
####################################################################

alias: 'Chiudi tenda veranda per pioggia o fresco'
initial_state: True
trigger:
  - platform: state
    entity_id: binary_sensor.rain
    from: 'off'
    to: 'on'
  - platform: numeric_state
    entity_id: sensor.veranda_temperature
    below: 24

condition:
  - condition: state
    entity_id: input_select.cover_veranda_state
    state: 'open'

action:
  - service: cover.open_cover
    entity_id: cover.veranda
  - service: input_select.select_option
    data:
      entity_id: input_select.cover_veranda_state
      option: 'closed'
  - service: notify.notifyglp
    data_template:
      message: "Tenda veranda chiusa, {{ states.sensor.dark_sky_precip_intensity.state }} mm di pioggia"
