#
# LoPresti smart home - automation configuration for Home Assistant
#
####################################################################

# abbassa la tenda d'estate durante il giorno, se c'e' qualcuno, temperatura > 25C & vento < 20 km/h
alias: 'Apri tenda veranda se fa caldo'
trigger:
  platform: time
  minutes: '/10'    # check every 10' to avoid fast loops in case of critical wind conditions

condition:
  - condition: time
    after: '08:15:00'
    before: '17:00:00'
  - condition: template
    value_template: '{{ now().month > 4 and (now().month < 10 or (now().month == 10 and now().day < 15)) }}'
  - condition: state
    entity_id: binary_sensor.presence
    state: 'on'
  - condition: state
    entity_id: input_select.cover_veranda_state
    state: 'closed'
  - condition: numeric_state
    entity_id: sensor.netatmo_terrace_gust_strength
    below: 20
  - condition: numeric_state
    entity_id: sensor.veranda_temperature
    above: 25

action:
  - service: cover.open_cover
    entity_id: cover.veranda
  - service: input_select.select_option
    data:
      entity_id: input_select.cover_veranda_state
      option: 'open'
