#
# LoPresti smart home - automation configuration for Home Assistant
#
####################################################################

# abbassa la tenda durante il giorno, se c'e' qualcuno, temperatura > 25C & vento < 20 km/h
alias: 'Apri tenda se fa caldo'
trigger:
  platform: time
  minutes: '/10'    # check every 10' to avoid fast loops in case of critical wind conditions

condition:
  - condition: time
    after: '08:15:00'
    before: '18:00:00'
  - condition: state
    entity_id: group.famiglia
    state: 'home'
  - condition: numeric_state
    entity_id: sensor.netatmo_terrace_gust_strength
    below: 20
  - condition: numeric_state
    entity_id: sensor.veranda_temperature
    above: 25

action:
  service: cover.open_cover
  entity_id: cover.veranda
