#
# LoPresti smart home - automation configuration for Home Assistant
#
####################################################################

# metti webcam in modo notte mezz'ora dopo il tramonto
alias: 'VerandaCam di sera'
initial_state: True
trigger:
  platform: sun
  event: sunset
  offset: "+00:30:00"

action:
  - service: homeassistant.turn_on
    entity_id: switch.verandacam_night_vision
