#
# LoPresti smart home - automation configuration for Home Assistant
#
####################################################################

# Alle 8 torna in modalita' normale e metti webcam in modo giorno
alias: 'VerandaCam di giorno'
initial_state: True
trigger:
# not using sunrise because most of the time homeassistant is off...
  - platform: time
    hours: 08
    minutes: 00

action:
  - service: input_select.select_option
    data:
      entity_id: input_select.statocasa
      option: 'Normale'
  - service: homeassistant.turn_off
    entity_id: switch.verandacam_night_vision
